/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package miniprojet_cadenas_andre;

/**
 *
 * @author maxim
 */
public class Cadenas extends javax.swing.JFrame {
    jeu maPartie = new jeu();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Cadenas.class.getName());

    /**
     * Creates new form Cadenas
     */
    public Cadenas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texte_intro = new javax.swing.JLabel();
        up_chiffre_1 = new javax.swing.JToggleButton();
        up_chiffre_2 = new javax.swing.JToggleButton();
        up_chiffre_3 = new javax.swing.JToggleButton();
        up_chiffre_4 = new javax.swing.JToggleButton();
        texte_chiffre_0 = new javax.swing.JLabel();
        texte_chiffre_1 = new javax.swing.JLabel();
        texte_chiffre_2 = new javax.swing.JLabel();
        texte_chiffre_3 = new javax.swing.JLabel();
        down_chiffre_1 = new javax.swing.JToggleButton();
        down_chiffre_2 = new javax.swing.JToggleButton();
        down_chiffre_3 = new javax.swing.JToggleButton();
        down_chiffre_4 = new javax.swing.JToggleButton();
        bouton_tester = new javax.swing.JToggleButton();
        texte_lbl_nb_chiffres_exacts = new javax.swing.JLabel();
        texte_nb_chiffres_exacts = new javax.swing.JLabel();
        texte_lbl_nombre_chiffres_haut = new javax.swing.JLabel();
        texte_nb_chiffres_haut = new javax.swing.JLabel();
        texte_lbl_nb_chiffres_bas = new javax.swing.JLabel();
        texte_nb_chiffres_bas = new javax.swing.JLabel();
        texte_tentatives = new javax.swing.JLabel();
        texte_score = new javax.swing.JLabel();
        bouton_recommencer = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        texte_intro.setText("Trouver le bon code en moins de 5 tentatives !");
        getContentPane().add(texte_intro, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 6, -1, -1));

        up_chiffre_1.setText("/\\");
            up_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    up_chiffre_1ActionPerformed(evt);
                }
            });
            getContentPane().add(up_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 50, 50, -1));

            up_chiffre_2.setText("/\\");
                up_chiffre_2.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        up_chiffre_2ActionPerformed(evt);
                    }
                });
                getContentPane().add(up_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 50, -1));

                up_chiffre_3.setText("/\\");
                    up_chiffre_3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            up_chiffre_3ActionPerformed(evt);
                        }
                    });
                    getContentPane().add(up_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 50, -1));

                    up_chiffre_4.setText("/\\");
                        up_chiffre_4.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                up_chiffre_4ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(up_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 50, -1));

                        texte_chiffre_0.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                        texte_chiffre_0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        texte_chiffre_0.setText("0");
                        texte_chiffre_0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                        texte_chiffre_0.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
                        getContentPane().add(texte_chiffre_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 30, 40));

                        texte_chiffre_1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                        texte_chiffre_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        texte_chiffre_1.setText("0");
                        texte_chiffre_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                        texte_chiffre_1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                        getContentPane().add(texte_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 30, 40));

                        texte_chiffre_2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                        texte_chiffre_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        texte_chiffre_2.setText("0");
                        texte_chiffre_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                        getContentPane().add(texte_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 30, 40));

                        texte_chiffre_3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                        texte_chiffre_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        texte_chiffre_3.setText("0");
                        texte_chiffre_3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                        getContentPane().add(texte_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 30, 40));

                        down_chiffre_1.setText("\\/");
                        down_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_1ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 50, -1));

                        down_chiffre_2.setText("\\/");
                        down_chiffre_2.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_2ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 50, -1));

                        down_chiffre_3.setText("\\/");
                        down_chiffre_3.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_3ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 50, -1));

                        down_chiffre_4.setText("\\/");
                        down_chiffre_4.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_4ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 50, -1));

                        bouton_tester.setText("Tester...");
                        bouton_tester.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bouton_testerActionPerformed(evt);
                            }
                        });
                        getContentPane().add(bouton_tester, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));

                        texte_lbl_nb_chiffres_exacts.setText("Nombre de chiffres exacts :");
                        getContentPane().add(texte_lbl_nb_chiffres_exacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

                        texte_nb_chiffres_exacts.setText("0");
                        getContentPane().add(texte_nb_chiffres_exacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, -1));

                        texte_lbl_nombre_chiffres_haut.setText("Nombre de chiffres trop hauts :");
                        getContentPane().add(texte_lbl_nombre_chiffres_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

                        texte_nb_chiffres_haut.setText("0");
                        getContentPane().add(texte_nb_chiffres_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, -1, -1));

                        texte_lbl_nb_chiffres_bas.setText("Nombre de chiffres trop bas :");
                        getContentPane().add(texte_lbl_nb_chiffres_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, 20));

                        texte_nb_chiffres_bas.setText("0");
                        getContentPane().add(texte_nb_chiffres_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, -1));

                        texte_tentatives.setText("Tentatives");
                        getContentPane().add(texte_tentatives, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, -1, -1));

                        texte_score.setText("0 sur 5");
                        texte_score.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                        getContentPane().add(texte_score, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 40, 20));

                        bouton_recommencer.setText("Recommencer");
                        getContentPane().add(bouton_recommencer, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, -1, -1));

                        pack();
                    }// </editor-fold>//GEN-END:initComponents

    private void down_chiffre_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_4ActionPerformed
String texte = texte_chiffre_3.getText();
int nombre = Integer.parseInt(texte);
nombre = nombre - 1;
if (nombre < 0) {
    nombre = 9;
}
texte_chiffre_3.setText(String.valueOf(nombre));        
    }//GEN-LAST:event_down_chiffre_4ActionPerformed

    private void up_chiffre_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_2ActionPerformed
String texte = texte_chiffre_1.getText();
int nombre = Integer.parseInt(texte);
nombre = nombre + 1;
if (nombre > 9) {
    nombre = 0;
}
texte_chiffre_1.setText(String.valueOf(nombre));    }//GEN-LAST:event_up_chiffre_2ActionPerformed

    private void up_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_1ActionPerformed
String texte = texte_chiffre_0.getText();

int nombre = Integer.parseInt(texte);

nombre = nombre + 1;

if (nombre > 9) {
    nombre = 0;
}
texte_chiffre_0.setText(String.valueOf(nombre));    }//GEN-LAST:event_up_chiffre_1ActionPerformed

    private void down_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_1ActionPerformed
String texte = texte_chiffre_0.getText();

int nombre = Integer.parseInt(texte);

nombre = nombre - 1;

if (nombre < 0) {
    nombre = 9;
}

texte_chiffre_0.setText(String.valueOf(nombre));        
    }//GEN-LAST:event_down_chiffre_1ActionPerformed

    private void down_chiffre_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_2ActionPerformed
String texte = texte_chiffre_1.getText();
int nombre = Integer.parseInt(texte);
nombre = nombre - 1;
if (nombre < 0) {
    nombre = 9;
}
texte_chiffre_1.setText(String.valueOf(nombre));    }//GEN-LAST:event_down_chiffre_2ActionPerformed

    private void down_chiffre_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_3ActionPerformed
String texte = texte_chiffre_2.getText();
int nombre = Integer.parseInt(texte);
nombre = nombre - 1;
if (nombre < 0) {
    nombre = 9;
}
texte_chiffre_2.setText(String.valueOf(nombre));        
    }//GEN-LAST:event_down_chiffre_3ActionPerformed

    private void bouton_testerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_testerActionPerformed
int[] proposition = new int[4];

proposition[0] = Integer.parseInt(texte_chiffre_0.getText());
proposition[1] = Integer.parseInt(texte_chiffre_1.getText());
proposition[2] = Integer.parseInt(texte_chiffre_2.getText());
proposition[3] = Integer.parseInt(texte_chiffre_3.getText());

int[] resultat = maPartie.verifierCombinaison(proposition);

texte_nb_chiffres_exacts.setText(String.valueOf(resultat[0])); 

texte_nb_chiffres_haut.setText(String.valueOf(resultat[1]));   

texte_nb_chiffres_bas.setText(String.valueOf(resultat[2]));    

int essais = maPartie.getTentativeActuelle();
int max = maPartie.getMaxTentatives();
texte_tentatives.setText(essais + " sur " + max);


if (resultat[0] == 4) {
    javax.swing.JOptionPane.showMessageDialog(this, "Bravo ! Vous avez trouvé le code !");
    bouton_tester.setEnabled(false); 
} 
else if (essais >= max) {
    javax.swing.JOptionPane.showMessageDialog(this, "Perdu ! Retentez votre chance.");
    bouton_tester.setEnabled(false); 
}       
    }//GEN-LAST:event_bouton_testerActionPerformed

    private void up_chiffre_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_3ActionPerformed
String texte = texte_chiffre_2.getText();
int nombre = Integer.parseInt(texte);
nombre = nombre + 1;
if (nombre > 9) {
    nombre = 0;
}
texte_chiffre_2.setText(String.valueOf(nombre));        // TODO add your handling code here:
    }//GEN-LAST:event_up_chiffre_3ActionPerformed

    private void up_chiffre_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_4ActionPerformed
String texte = texte_chiffre_3.getText();
int nombre = Integer.parseInt(texte);
nombre = nombre + 1;
if (nombre > 9) {
    nombre = 0;
}
texte_chiffre_3.setText(String.valueOf(nombre));        // TODO add your handling code here:
    }//GEN-LAST:event_up_chiffre_4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Cadenas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton bouton_recommencer;
    private javax.swing.JToggleButton bouton_tester;
    private javax.swing.JToggleButton down_chiffre_1;
    private javax.swing.JToggleButton down_chiffre_2;
    private javax.swing.JToggleButton down_chiffre_3;
    private javax.swing.JToggleButton down_chiffre_4;
    private javax.swing.JLabel texte_chiffre_0;
    private javax.swing.JLabel texte_chiffre_1;
    private javax.swing.JLabel texte_chiffre_2;
    private javax.swing.JLabel texte_chiffre_3;
    private javax.swing.JLabel texte_intro;
    private javax.swing.JLabel texte_lbl_nb_chiffres_bas;
    private javax.swing.JLabel texte_lbl_nb_chiffres_exacts;
    private javax.swing.JLabel texte_lbl_nombre_chiffres_haut;
    private javax.swing.JLabel texte_nb_chiffres_bas;
    private javax.swing.JLabel texte_nb_chiffres_exacts;
    private javax.swing.JLabel texte_nb_chiffres_haut;
    private javax.swing.JLabel texte_score;
    private javax.swing.JLabel texte_tentatives;
    private javax.swing.JToggleButton up_chiffre_1;
    private javax.swing.JToggleButton up_chiffre_2;
    private javax.swing.JToggleButton up_chiffre_3;
    private javax.swing.JToggleButton up_chiffre_4;
    // End of variables declaration//GEN-END:variables
}
