/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package miniprojet_cadenas_andre;

/**
 *
 * @author maxim
 */
public class Cadenas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Cadenas.class.getName());

    /**
     * Creates new form Cadenas
     */
    public Cadenas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texte_intro = new javax.swing.JLabel();
        up_chiffre_1 = new javax.swing.JToggleButton();
        up_chiffre_2 = new javax.swing.JToggleButton();
        up_chiffre_3 = new javax.swing.JToggleButton();
        up_chiffre_4 = new javax.swing.JToggleButton();
        texte_chiffre_0 = new javax.swing.JLabel();
        texte_chiffre_1 = new javax.swing.JLabel();
        texte_chiffre_2 = new javax.swing.JLabel();
        texte_chiffre_3 = new javax.swing.JLabel();
        up_chiffre_5 = new javax.swing.JToggleButton();
        up_chiffre_6 = new javax.swing.JToggleButton();
        up_chiffre_7 = new javax.swing.JToggleButton();
        up_chiffre_8 = new javax.swing.JToggleButton();
        bouton_tester = new javax.swing.JToggleButton();
        texte_lbl_nb_chiffres_exacts = new javax.swing.JLabel();
        texte_nb_chiffres_exacts = new javax.swing.JLabel();
        texte_lbl_nombre_chiffres_haut = new javax.swing.JLabel();
        texte_nb_chiffres_haut = new javax.swing.JLabel();
        texte_lbl_nb_chiffres_bas = new javax.swing.JLabel();
        texte_nb_chiffres_bas = new javax.swing.JLabel();
        texte_tentatives = new javax.swing.JLabel();
        texte_score = new javax.swing.JLabel();
        bouton_recommencer = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        texte_intro.setText("Trouver le bon code en moins de 5 tentatives !");
        getContentPane().add(texte_intro, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 6, -1, -1));

        up_chiffre_1.setText("\\/");
        up_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up_chiffre_1ActionPerformed(evt);
            }
        });
        getContentPane().add(up_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 40, -1));

        up_chiffre_2.setText("/\\");
            up_chiffre_2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    up_chiffre_2ActionPerformed(evt);
                }
            });
            getContentPane().add(up_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 40, -1));

            up_chiffre_3.setText("/\\");
                getContentPane().add(up_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 40, -1));

                up_chiffre_4.setText("/\\");
                    getContentPane().add(up_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

                    texte_chiffre_0.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                    texte_chiffre_0.setText("0");
                    texte_chiffre_0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                    getContentPane().add(texte_chiffre_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 30, 40));

                    texte_chiffre_1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                    texte_chiffre_1.setText("0");
                    texte_chiffre_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                    texte_chiffre_1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                    getContentPane().add(texte_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 30, 40));

                    texte_chiffre_2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                    texte_chiffre_2.setText("0");
                    texte_chiffre_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                    getContentPane().add(texte_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 30, 40));

                    texte_chiffre_3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                    texte_chiffre_3.setText("0");
                    texte_chiffre_3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                    getContentPane().add(texte_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 30, 40));

                    up_chiffre_5.setText("/\\");
                        up_chiffre_5.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                up_chiffre_5ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(up_chiffre_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

                        up_chiffre_6.setText("\\/");
                        up_chiffre_6.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                up_chiffre_6ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(up_chiffre_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 40, -1));

                        up_chiffre_7.setText("\\/");
                        up_chiffre_7.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                up_chiffre_7ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(up_chiffre_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 40, -1));

                        up_chiffre_8.setText("\\/");
                        up_chiffre_8.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                up_chiffre_8ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(up_chiffre_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 40, -1));

                        bouton_tester.setText("Tester...");
                        bouton_tester.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bouton_testerActionPerformed(evt);
                            }
                        });
                        getContentPane().add(bouton_tester, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));

                        texte_lbl_nb_chiffres_exacts.setText("Nombre de chiffres exacts :");
                        getContentPane().add(texte_lbl_nb_chiffres_exacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

                        texte_nb_chiffres_exacts.setText("0");
                        getContentPane().add(texte_nb_chiffres_exacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, -1));

                        texte_lbl_nombre_chiffres_haut.setText("Nombre de chiffres trop hauts :");
                        getContentPane().add(texte_lbl_nombre_chiffres_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

                        texte_nb_chiffres_haut.setText("0");
                        getContentPane().add(texte_nb_chiffres_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, -1, -1));

                        texte_lbl_nb_chiffres_bas.setText("Nombre de chiffres trop bas :");
                        getContentPane().add(texte_lbl_nb_chiffres_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, 20));

                        texte_nb_chiffres_bas.setText("0");
                        getContentPane().add(texte_nb_chiffres_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, -1));

                        texte_tentatives.setText("Tentatives");
                        getContentPane().add(texte_tentatives, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, -1, -1));

                        texte_score.setText("0 sur 5");
                        texte_score.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                        getContentPane().add(texte_score, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 40, 20));

                        bouton_recommencer.setText("Recommencer");
                        getContentPane().add(bouton_recommencer, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, -1, -1));

                        pack();
                    }// </editor-fold>//GEN-END:initComponents

    private void up_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_up_chiffre_1ActionPerformed

    private void up_chiffre_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_up_chiffre_2ActionPerformed

    private void up_chiffre_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_up_chiffre_5ActionPerformed

    private void up_chiffre_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_up_chiffre_6ActionPerformed

    private void up_chiffre_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_up_chiffre_7ActionPerformed

    private void up_chiffre_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_up_chiffre_8ActionPerformed

    private void bouton_testerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_testerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bouton_testerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Cadenas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton bouton_recommencer;
    private javax.swing.JToggleButton bouton_tester;
    private javax.swing.JLabel texte_chiffre_0;
    private javax.swing.JLabel texte_chiffre_1;
    private javax.swing.JLabel texte_chiffre_2;
    private javax.swing.JLabel texte_chiffre_3;
    private javax.swing.JLabel texte_intro;
    private javax.swing.JLabel texte_lbl_nb_chiffres_bas;
    private javax.swing.JLabel texte_lbl_nb_chiffres_exacts;
    private javax.swing.JLabel texte_lbl_nombre_chiffres_haut;
    private javax.swing.JLabel texte_nb_chiffres_bas;
    private javax.swing.JLabel texte_nb_chiffres_exacts;
    private javax.swing.JLabel texte_nb_chiffres_haut;
    private javax.swing.JLabel texte_score;
    private javax.swing.JLabel texte_tentatives;
    private javax.swing.JToggleButton up_chiffre_1;
    private javax.swing.JToggleButton up_chiffre_2;
    private javax.swing.JToggleButton up_chiffre_3;
    private javax.swing.JToggleButton up_chiffre_4;
    private javax.swing.JToggleButton up_chiffre_5;
    private javax.swing.JToggleButton up_chiffre_6;
    private javax.swing.JToggleButton up_chiffre_7;
    private javax.swing.JToggleButton up_chiffre_8;
    // End of variables declaration//GEN-END:variables
}
