/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author maxim
 */
public class Interface extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interface.class.getName());
    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ZoneTextes = new javax.swing.JLabel();
        ZoneBoutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ZoneTextes.setBackground(new java.awt.Color(255, 255, 255));
        ZoneTextes.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        ZoneTextes.setForeground(new java.awt.Color(255, 51, 51));
        ZoneTextes.setText("Bonjour");
        getContentPane().add(ZoneTextes, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        ZoneBoutton.setText("Validez Ici");
        ZoneBoutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZoneBouttonActionPerformed(evt);
            }
        });
        getContentPane().add(ZoneBoutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 175, -1, 33));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ZoneBouttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZoneBouttonActionPerformed
    ZoneTextes.setText("hello");

    }//GEN-LAST:event_ZoneBouttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interface().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ZoneBoutton;
    private javax.swing.JLabel ZoneTextes;
    // End of variables declaration//GEN-END:variables
}
