/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.util.ArrayList;
/**
 *
 * @author maxim
 */
public class FenetreQuiz extends javax.swing.JFrame {
    
    ArrayList<Question> listeQuestions = new ArrayList<>();
    
    int indexQuestionCourante = 0;
    int score = 0;
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FenetreQuiz.class.getName());
    
    
    
    /**
     * Creates new form FenetreQuiz
     */
    public FenetreQuiz() {
        initComponents();
        initialiserQuestions();
        afficherQuestionCourante();
        jButton1.setFocusPainted(false);
        jButton2.setFocusable(false);
        jButton3.setFocusable(false);
        jButton4.setFocusable(false);
        jButton5.setFocusable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("lblQuestion");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 51, -1, -1));

        jButton1.setText("btnRep1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 84, -1, -1));

        jButton2.setText("btnRep2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 84, -1, -1));

        jButton3.setText("btnRep3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 125, -1, -1));

        jButton4.setText("btnRep4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 125, -1, -1));

        jLabel2.setText("lblMessage");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 179, -1, -1));

        jButton5.setText("Question Suivante");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 258, -1, -1));

        jLabel3.setText("Score :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 217, 210, 27));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
verifierReponse(2);    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
indexQuestionCourante++;
    
    if (indexQuestionCourante < listeQuestions.size()) {
        afficherQuestionCourante(); 
        
    } else {
        jLabel2.setText("Quiz terminé !");
        
        jLabel3.setText("Final : " + score + " / " + listeQuestions.size());
        
        jButton5.setEnabled(false);
        
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
    }    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    verifierReponse(1);    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    verifierReponse(3);    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    verifierReponse(4);    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FenetreQuiz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

private void initialiserQuestions() {
        listeQuestions.add(new Question("Quel mot-clé pour l'héritage ?", "extends", "implements", "inherits", "super", 1));
        listeQuestions.add(new Question("Variable pour vrai/faux ?", "int", "String", "boolean", "float", 3));
        listeQuestions.add(new Question("Point d'entrée du programme ?", "start()", "run()", "init()", "main()", 4));
        listeQuestions.add(new Question("Déclarer une constante ?", "const", "final", "static", "var", 2));
        listeQuestions.add(new Question("Pas un type primitif ?", "int", "double", "String", "char", 3));
    }

    private void afficherQuestionCourante() {
        if (indexQuestionCourante < listeQuestions.size()) {
            Question q = listeQuestions.get(indexQuestionCourante);
            
            jLabel1.setText(q.getIntitule());
            jButton1.setText(q.getProposition1());
            jButton2.setText(q.getProposition2());
            jButton3.setText(q.getProposition3());
            jButton4.setText(q.getProposition4());
            
            jButton1.setBackground(null);
            jButton2.setBackground(null);
            jButton3.setBackground(null);
            jButton4.setBackground(null);
            
            jButton1.setEnabled(true);
            jButton2.setEnabled(true);
            jButton3.setEnabled(true);
            jButton4.setEnabled(true);
            jLabel2.setText(""); 
        }
    }
    private void verifierReponse(int reponseUtilisateur) {
        Question q = listeQuestions.get(indexQuestionCourante);
        int bonneReponse = q.getIndexBonneReponse();

        javax.swing.JButton boutonClique = null;
        if (reponseUtilisateur == 1) boutonClique = jButton1;
        if (reponseUtilisateur == 2) boutonClique = jButton2;
        if (reponseUtilisateur == 3) boutonClique = jButton3;
        if (reponseUtilisateur == 4) boutonClique = jButton4;

        if (reponseUtilisateur == bonneReponse) {
            jLabel2.setText("Bonne réponse !");
            score++;
            jLabel3.setText("Score : " + score);
            
            if (boutonClique != null) boutonClique.setBackground(java.awt.Color.GREEN);

            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
        } else {
            jLabel2.setText("Faux ! Essaie encore...");
            
            if (boutonClique != null) boutonClique.setBackground(java.awt.Color.RED);

            if (boutonClique != null) boutonClique.setEnabled(false);
        }
    }
}

